### ISSUE TITLE
Error al crear una mascota con un usuario comun

### ISSUE THREAD

**Issue by emiarias** [ezeamin/rollingVetServer#1]
Al cargar los datos con un nuevo usuario, no podemos dar de alta una mascota
![image](https://user-images.githubusercontent.com/18445151/157340690-5942c5a1-c838-445f-83bd-69de25e96331.png)
![image](https://user-images.githubusercontent.com/18445151/157340694-10a8f2dc-06ec-497f-9113-3bd60b39ddef.png)

**Comment by ezeamin** [comment]
Buenas, estoy al tanto y revisandolo. Hago un push cuando lo corrija. Gracias

**Comment by ezeamin** [comment]
Se corrigió el error. Cambie el codigo de validacion backend hace unos dias y no tuve el tiempo de testearlo correctamente. Solucionando algunas excepciones que ocurrian, ya esta en funcionamiento.
